### ISSUE TITLE
Auto start the Pi-MP3 Player on startup

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi-MP3_Player#11]
I followed the instructions included but it doesn't work (goes to Home Folder), perhaps because I'm using a Raspberry Pi 4B with 4gb and Raspberry Pi OS Bookworm 64 bit, if I remember when I used a Raspberry Pi3B and OS  Bullseye it worked

**Comment by Gordon999** [comment]
If using BOOKWORM you could switch to X11. sudo raspi-config, choose advanced , choose 6A X11 option, reboot.

Or if using BOOKWORM and labwc...  (note: change XXXX to your username)

 sudo nano /home/XXXX/.config/labwc/autostart

type in...

/usr/bin/python3 /home/XXXX/MP3_Player.py

press Ctrl and X,  press Y, press Enter  to save..

Reboot



https://forums.raspberrypi.com/viewtopic.php?t=314455

**Comment by Gordon999** [comment]
Fixed ?

**Comment by Rich1975** [comment]
Thank you for your patience!, if I may make 1 more suggestion ... in the program "Drive:   (lots of space)    /home/rich/Music" is showing its missing the "c " in "Music" if that could be fixed and even moving the "/home/rich...." closer to word "Drive:".
The Auto start works after X11 setting, the Bluetooth works, and the Rotary encoders work.

My setup is 
Raspberry Pi 4B with 4gb, Os is Bookworm 64 bit, Innomaker 80watt Amp hat, and a 15v 3amp power supply. Could not use a Raspberry Pi 5 and the INNOMAKER amp, kept getting low power message, so I switched to Pi4 and all is well
Thanks

**Comment by Gordon999** [comment]
try v17.87

**Comment by Rich1975** [comment]
Still not showing the "c" for "/home/rich/Musi" and could move a few more spaces left closer to "Drive: ", This is the location of my music files.

**Comment by Gordon999** [comment]
try v17.88

**Comment by Rich1975** [comment]
That works!, Noticed the addition on line 33 "ext_buttons = 0", so next I would set aside the Touch screen and rotary encoders and wire up for Non touch screen and switches to see how that works.

**Comment by Gordon999** [comment]
I added the ext_buttons option because if you connect rotaries and then set rotary = 0 the code won't work. Helps me when testing.

You can't use the rotarys and ext buttons together.
